Traceback (most recent call last):
  File "c:\Users\User\Documents\GitHub\sc2ai\order-action\trainppo.py", line 49, in <module>
    model = PPO.load(last_model_path, env, tensorboard_log=logdir)
  File "C:\Users\User\Miniconda3\lib\site-packages\stable_baselines3\common\base_class.py", line 679, in load
    data, params, pytorch_variables = load_from_zip_file(
  File "C:\Users\User\Miniconda3\lib\site-packages\stable_baselines3\common\save_util.py", line 390, in load_from_zip_file
    load_path = open_path(load_path, "r", verbose=verbose, suffix="zip")
  File "C:\Users\User\Miniconda3\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\User\Miniconda3\lib\site-packages\stable_baselines3\common\save_util.py", line 234, in open_path_str
    return open_path(pathlib.Path(path), mode, verbose, suffix)
  File "C:\Users\User\Miniconda3\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\User\Miniconda3\lib\site-packages\stable_baselines3\common\save_util.py", line 258, in open_path_pathlib
    path = path.open("rb")
  File "C:\Users\User\Miniconda3\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\Documents\\GitHub\\sc2ai\\models\\1700693617'